### ISSUE TITLE
Exception on Clicking See All Interests

### ISSUE THREAD

**Issue by brandonarrindell** [addshore/browser-facebook-advert-interest-cleaner#4]
`Uncaught (in promise) DOMException: Failed to execute 'evaluate' on 'Document': The string '//span[translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZİ','abcdefghijklmnopqrstuvwxyzi') = 'translate(See All Interests,'ABCDEFGHIJKLMNOPQRSTUVWXYZİ','abcdefghijklmnopqrstuvwxyzi')']' is not a valid XPath expression.
    at clickSeeAllInterestsButton (chrome-extension://nheaildopjpofjpkeihboipgnagofndi/scripts/adpreferences-ad_settings.js:210:29)
    at HTMLInputElement.<anonymous> (chrome-extension://nheaildopjpofjpkeihboipgnagofndi/scripts/adpreferences-ad_settings.js:231:11)`

**Comment by addshore** [comment]
I believe this was broken in https://github.com/addshore/browser-facebook-advert-interest-cleaner/commit/f57dd18b464f88d94c849be5497f4a19cde36daf and fixed in https://github.com/addshore/browser-facebook-advert-interest-cleaner/commit/8a5adcd8f11cd2a0f225ae5678467137dcacca17

I'll be pushing out 1.1.0 today which has that fix in it (as well as some more changes)

**Comment by addshore** [comment]
Just pushed 1.1.0 to all the stores.
If you are super keen to test / use it you can find a zip to install at https://github.com/addshore/browser-facebook-advert-interest-cleaner/releases/tag/v1.1.0
